app_todo_v02/urls.py
from django.urls import path
from . import views

app_name = 'app_todo_v02'

urlpatterns = [
    path("", views.index, name='index'),
    path("detail_task/<int:pk>/", views.detail_task, name='detail_task'),
    path('create_task/', views.create_task, name='create_task'),
    path('update_task/<int:pk>/', views.update_task, name='update_task'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('app_todo_v02.urls', namespace='app_todo_v02')),
]

app_todo_v02/models.py
from django.db import models
from django.urls import reverse

class Task(models.Model):
    title = models.CharField(max_length=50)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    completed = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse("detail_task", kwargs={"pk": self.pk})
    
    def __str__(self):
        return self.title
    

app_todo_v02/forms.py
from django import forms
from . models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = '__all__'

app_todo_v02/views.py
from django.shortcuts import render, get_object_or_404, redirect

from .models import Task
from . forms import TaskForm


def index(request):
    #tasks = Task.objects.all()
    tasks = Task.objects.filter(completed=False)
    context = {
        'tasks':tasks
    }
    return render(request, 'app_todo_v02/index.html', context)

def detail_task(request, pk):
    context = {'task': get_object_or_404(Task, pk=pk)}
    return render(request, 'app_todo_v02/detail_task.html', context)

def create_task(request):
    form = TaskForm(request.POST)
    if request.method =='POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('app_todo_v02:index')

    context = {'form':form}
    return render(request, 'app_todo_v02/create_task.html', context)

def update_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    form = TaskForm(instance=task)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            #return redirect('app_todo_v02:detail_task', args=(pk, pk))
            return redirect('app_todo_v02:index')
    context = {'form':form}
    return render(request, 'app_todo_v02/create_task.html', context)

app_todo_v02/templates/app_todo_v02/create_task.html
{% extends 'base.html' %}

{% block content %}

    <form method='POST' action="">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-info" type="submit" name="Create Task">
    </form>

{% endblock %}

app_todo_v02/templates/app_todo_v02/detail_task.html
{% extends 'base.html' %}

{% block content %}

    <h1>
        <a href="{% url 'app_todo_v02:update_task' pk=task.pk %}">
        {{ task.title }}
    </a></h1>
    <p>{{ task.body }}</p>

{% endblock %}

app_todo_v02/templates/app_todo_v02/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<a href={% url "app_todo_v02:create_task" %}>Create New</a>

    {% if tasks %}

    {% for task in tasks %}
        <h1>
            {% comment %} <a href="{#{ task.get_absolute_url }#}"> {% endcomment %}
                <a href="{% url 'app_todo_v02:detail_task' pk=task.pk %}">
            {{ task.title }}
        </a></h1>
        <p>{{ task.body|truncatechars:50 }}</p>
    {% endfor %}

    {% endif %}

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>
       
        <div class="container">
            <div class="row">
              <div class="col">

                    {% block content %}
                    {% endblock %}

                </div>
            </div>
        </div>

        
        <script src="" async defer></script>
    </body>
</html>